name: BlitzBrightPlus
version: 1.0.0
main: in.lunaty.asher.BlitzBrightPlus
api-version: 1.21
commands:
  fb:
    description: Toggle BlitzBrightPlus
    usage: /fb
    aliases: [blitzbright, light]
permissions:
  blitzbright.use:
    description: Allows toggling brightness
    default: true