name: BlitzBrightPlus
version: 1.1.0
main: in.lunaty.asher.BlitzBrightPlus
api-version: 1.21
commands:
  fb:
    description: Toggle night vision
    usage: /fb [reload]
    aliases: [light, nightvision, bbp]
permissions:
  blitzbright.use:
    description: Default permission to use the toggle
    default: true
  blitzbright.reload:
    description: Allows reloading the config
    default: op