name: BlitzBrightPlus
version: 1.1.0
main: in.lunaty.asher.BlitzBrightPlus
api-version: 1.21
commands:
  fb:
    description: Toggle Brightness
    usage: /fb
    aliases: [blitzbright, light]
permissions:
  blitzbright.use:
    default: true
  blitzbright.reload:
    default: op